# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            GujjuCoders
tagline:          'Gujjus by heart, Indians by passion, BITSians by destiny.'
description:      'Gujjus by heart, Indians by passion, BITSians by destiny.'
url:              "http://localhost:4000"
baseurl:	         ""
paginate:            5

gems:
  - jemoji
  - jekyll-gist
  - jekyll-paginate